# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome1: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello2:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world2:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  print_env1:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $env1
workflows:
  # Name the workflow "welcome2"
  welcome1:
    # Run the welcome/run job in its own container
    jobs:
      - welcome1/run
      - print_save_hello_world_output
      - print_output_file
      - print_env1 
      - print_hello2
      - print_world2:
          requires:
            - print_hello2
      
